In [1]:
import torch

print(torch.__version__)

2.4.0


## Introduction to Tensors

### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# number of dimensions
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 3, 6])
vector

tensor([7, 3, 6])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:

MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[0][1]

tensor([4, 5, 6])

In [18]:
TENSOR[0][1][2]

tensor(6)

In [19]:
TENSOR[0][1][2].item()

6

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [20]:
# Create a random tensor of shape (2, 4)
random_tensor = torch.rand(2, 4)
random_tensor

tensor([[0.2469, 0.0116, 0.9666, 0.8845],
        [0.2271, 0.8596, 0.2301, 0.4533]])

In [21]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels(Red, Greeen, Blue)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [22]:
torch.rand(3,3)

tensor([[0.1362, 0.8470, 0.6823],
        [0.6114, 0.1920, 0.3850],
        [0.9201, 0.7953, 0.2986]])

### Zeros and ones

In [23]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(2,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensor of all ones
ones = torch.ones(size=(2,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [28]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
one_to_twenty = torch.arange(start=1, end=21, step=3)
one_to_twenty

tensor([ 1,  4,  7, 10, 13, 16, 19])

In [30]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Note: Tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning:

* 1. Tensors not right datatype
* 2. Tensors not right shape
* 3. Tensors not on the right device

In [31]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # tensor datatype(e.g. float16 or float32)
                               device=None, # cpu or cuda
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [37]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4635, 0.1282, 0.5253, 0.2022],
        [0.5279, 0.6467, 0.8696, 0.7617],
        [0.3573, 0.5966, 0.1761, 0.6289]])

In [38]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [39]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4635, 0.1282, 0.5253, 0.2022],
        [0.5279, 0.6467, 0.8696, 0.7617],
        [0.3573, 0.5966, 0.1761, 0.6289]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors(tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [40]:
# Creating a tensor and add 6 to it
tensor = torch.tensor([1, 2, 3])
tensor + 6

tensor([7, 8, 9])

In [41]:
# Multiply tensor by 2
tensor * 2

tensor([2, 4, 6])

In [42]:
# Subtract 7
tensor - 7

tensor([-6, -5, -4])

In [43]:
# Pytorch built-in functions
torch.mul(tensor, 3)

tensor([3, 6, 9])

In [44]:
torch.add(tensor, 5)

tensor([6, 7, 8])