In [1]:
import torch

print(torch.__version__)

2.4.0


## Introduction to Tensors

### Creating Tensors

In [53]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [54]:
# number of dimensions
scalar.ndim

0

In [55]:
# Get tensor back as python int
scalar.item()

7

In [56]:
# Vector
vector = torch.tensor([7, 3, 6])
vector

tensor([7, 3, 6])

In [57]:
vector.ndim

1

In [58]:
vector.shape

torch.Size([3])

In [59]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [60]:
MATRIX.ndim

2

In [61]:

MATRIX.shape

torch.Size([2, 2])

In [62]:
MATRIX[0]

tensor([7, 8])

In [63]:
MATRIX[1]

tensor([ 9, 10])

In [64]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [65]:
TENSOR.shape

torch.Size([1, 3, 3])

In [66]:
TENSOR.ndim

3

In [67]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
TENSOR[0][1]

tensor([4, 5, 6])

In [69]:
TENSOR[0][1][2]

tensor(6)

In [70]:
TENSOR[0][1][2].item()

6

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [71]:
# Create a random tensor of shape (2, 4)
random_tensor = torch.rand(2, 4)
random_tensor

tensor([[0.6059, 0.5596, 0.2717, 0.6697],
        [0.0243, 0.2744, 0.0405, 0.3489]])

In [72]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels(Red, Greeen, Blue)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [73]:
torch.rand(3,3)

tensor([[0.9110, 0.9715, 0.8249],
        [0.2775, 0.7262, 0.3972],
        [0.7195, 0.8730, 0.7113]])

### Zeros and ones

In [74]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(2,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [75]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [76]:
# Create a tensor of all ones
ones = torch.ones(size=(2,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [77]:
ones.dtype

torch.float32

In [78]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [79]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
one_to_twenty = torch.arange(start=1, end=21, step=3)
one_to_twenty

tensor([ 1,  4,  7, 10, 13, 16, 19])

In [81]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Note: Tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning:

* 1. Tensors not right datatype
* 2. Tensors not right shape
* 3. Tensors not on the right device

In [82]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # tensor datatype(e.g. float16 or float32)
                               device=None, # cpu or cuda
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [83]:
float_32_tensor.dtype

torch.float32

In [84]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [85]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [86]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [87]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [88]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7812, 0.2557, 0.5123, 0.1848],
        [0.3839, 0.6319, 0.2450, 0.1865],
        [0.9429, 0.0652, 0.3094, 0.0138]])

In [89]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [90]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7812, 0.2557, 0.5123, 0.1848],
        [0.3839, 0.6319, 0.2450, 0.1865],
        [0.9429, 0.0652, 0.3094, 0.0138]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors(tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [91]:
# Creating a tensor and add 6 to it
tensor = torch.tensor([1, 2, 3])
tensor + 6

tensor([7, 8, 9])

In [92]:
# Multiply tensor by 2
tensor * 2

tensor([2, 4, 6])

In [93]:
# Subtract 7
tensor - 7

tensor([-6, -5, -4])

In [94]:
# Pytorch built-in functions
torch.mul(tensor, 3)

tensor([3, 6, 9])

In [95]:
torch.add(tensor, 5)

tensor([6, 7, 8])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(2,3) @ (3,2)` will work
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions:**
* `(2,3) @ (3,2)` -> `(2,2)`

In [96]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [97]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [98]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [99]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [100]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [101]:
torch.rand(1,2) @ torch.rand(2,1)

tensor([[0.7071]])

### one of the most common errors in deep learning: shape errors

In [102]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[5, 8],
                         [6, 9],
                         [7, 10]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issue, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [103]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 5,  6,  7],
         [ 8,  9, 10]]),
 torch.Size([2, 3]))

In [104]:
tensor_B, tensor_B.shape

(tensor([[ 5,  8],
         [ 6,  9],
         [ 7, 10]]),
 torch.Size([3, 2]))

In [105]:
tensor_A.shape

torch.Size([3, 2])

In [106]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### Finding the min, max, sum, mean, etc (tensor aggregation)

In [116]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [117]:
# find the min and max
x.min(), torch.min(x), x.max(), torch.max(x)

(tensor(1), tensor(1), tensor(91), tensor(91))

In [118]:
# find the mean( torch.mean() function requires a tensor of float32 datatype to work)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [119]:
# Find the sum
x.sum(), torch.sum(x)

(tensor(460), tensor(460))

### Finding the positional min and max

In [120]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [121]:
# Find the position in tensor that has the minimum value with argmin() - > returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [123]:
# minimum value of the tensor
x[0]

tensor(1)

In [124]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [125]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted(swapped) in a certain way

In [132]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [133]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [134]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [135]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [140]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [141]:
# Stack tensors side by side
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [142]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [143]:
x_reshaped.shape

torch.Size([1, 9])

In [144]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [146]:
x_reshaped.squeeze().shape

torch.Size([9])

In [147]:
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [151]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

x_unsqueezed2 = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor_2: {x_unsqueezed2}")
print(f"\nNew shape_2: {x_unsqueezed2.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])

New tensor_2: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

New shape_2: torch.Size([9, 1])


In [152]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))  # [Height, Width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # Shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (Selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [2]:
# Creating a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [4]:
x[0, 0]

tensor([1, 2, 3])

In [5]:
x[0, 0 ,0]

tensor(1)

In [6]:
x[0][0][0]

tensor(1)

In [8]:
# Get all values of 0th and 1st dimensions but only index 2 of 2nd dimension
x[:, :, 2]

tensor([[3, 6, 9]])

In [9]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [10]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])