In [1]:
import torch

print(torch.__version__)

2.4.0


## Introduction to Tensors

### Creating Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# number of dimensions
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [13]:
# Vector
vector = torch.tensor([7, 3, 6])
vector

tensor([7, 3, 6])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([3])

In [16]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
MATRIX.ndim

2

In [18]:

MATRIX.shape

torch.Size([2, 2])

In [19]:
MATRIX[0]

tensor([7, 8])

In [20]:
MATRIX[1]

tensor([ 9, 10])

In [21]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR.ndim

3

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
TENSOR[0][1]

tensor([4, 5, 6])

In [28]:
TENSOR[0][1][2]

tensor(6)

In [29]:
TENSOR[0][1][2].item()

6

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [32]:
# Create a random tensor of shape (2, 4)
random_tensor = torch.rand(2, 4)
random_tensor

tensor([[0.7748, 0.7000, 0.4054, 0.6344],
        [0.6199, 0.7316, 0.5159, 0.6425]])

In [31]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels(Red, Greeen, Blue)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)